#ifndef LAB2_ASTNODETYPE_HH
#define LAB2_ASTNODETYPE_HH

#include <iostream>

enum class ASTNodeType {
    Identifier,

    BoolLiteral,
    IntegerLiteral,
    RealLiteral,
    ImaginaryLiteral,
    InterpretedStringLiteral,
    UninterpretedStringLiteral,
    InterpretedBytesLiteral,
    UninterpretedBytesLiteral,

    Assignment,
    CompoundAssignment,
    RangeSpecifier,
    HalfOpenRangeSpecifier,
    RangeDomainStrideSpecifier,
    RangeCount,
    VariableArgumentLists,
    Plus,
    Minus,
    Multiplication,
    Division,
    Modulus,
    Exponentiation,
    BitwiseComplement,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    BitwiseShift,
    ExclamationMark,
    LogicalAnd,
    LogicalOr,
    OrderedComp,
    EqualityComp,
    By,
    TypeSpecifier,
    StatementSeparator,
    ExpressionSeparator,
    MemberAccess,
    Column,
    TypeQuery,

    LeftRoundBracket,
    RightRoundBracket,
    LeftSquareBracket,
    RightSquareBracket,
    LeftCurlyBracket,
    RightCurlyBracket,

    If,
    Then,
    Else,
    Var,
    Const,
    While,
    Do,
    For,
    In,
    Zip,
    Public,
    Private,
    Config,
    Extern,
    Export,
    Param,
    Ref,
    Void,
    Nothing,
    Bool,
    Int,
    Uint,
    Real,
    Imag,
    Complex,
    String,
    Bytes,
    Enum,
    Record,
    Class,
    Owned,
    Shared,
    Unmanaged,
    Borrowed,
    Out,
    Inout,
    Type,
    Inline,
    Override,
    Proc,
    Iter,
    Where,
    New,
    RangeLiteral,
    UnaryExpression,
    BinaryExpression,
    CallExpression,
    NamedExpressionList,
    FieldAccessExpression,
    MethodCallExpression,
    NewExpression,
    BlockStatement,
    ExpressionStatement,
    AssignmentStatement,
    ConditionalStatement,
    CtrlDecl,
    WhileDoStatement,
    DoWhileStatement,
    ForStatement,
    IdentifierList,
    TupleGroupedIdentifierList,
    ExpressionList,
    VariableDeclarationStatement,
    VariableKind,
    VariableDeclarationList,
    VariableDeclaration,
    PrimitiveType,
    ClassDeclarationStatement,
    ClassStatementList,
    MethodDeclarationStatement,
    Intent,
    ArgumentList,
    Formal,
    DefaultExpression,
    VariableArgumentExpression,
    TypeBinding,
    WhereClause,
    ClassType,
    Statements
};

std::ostream& operator<<(std::ostream& out, const ASTNodeType& node);


#endif //LAB2_ASTNODETYPE_HH
